name: Build Images
on:
    push:
        branches:
            - main
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install Bunjs
        run: bun install
      - name: Create images
        run: bun index.js
      - name: Upload folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./img/*

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
      
